---
title: "ACMTF_interpretation"
output: html_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(parafac4microbiome)
library(ggpubr)
library(ggrepel)
```


```{r load ACMTF model}
A = read.csv("./20241031_ACMTF_func/Athina_ACMTF_A.csv",header=FALSE) %>% as_tibble()
B = read.csv("./20241031_ACMTF_func/Athina_ACMTF_B.csv",header=FALSE) %>% as_tibble()
C = read.csv("./20241031_ACMTF_func/Athina_ACMTF_C.csv",header=FALSE) %>% as_tibble()
D = read.csv("./20241031_ACMTF_func/Athina_ACMTF_D.csv",header=FALSE) %>% as_tibble()

subjectMeta = read.csv("./20241031_ACMTF_func/Athina_homogenized_subjectMeta.csv",header=FALSE) %>% as_tibble()
colnames(subjectMeta) = c("subject", "Symptomatic")
taxonomy = read.csv("./20241031_ACMTF_func/Athina_taxonomy.csv",header=FALSE) %>% as_tibble()
colnames(taxonomy) = c("KO", "Description")
time = read.csv("./20241031_ACMTF_func/Athina_time.csv",header=FALSE) %>% as_tibble()
colnames(time) = c("extraction")
cytokines = read.csv("./20241031_ACMTF_func/Athina_cytokines.csv",header=FALSE) %>% as_tibble()
colnames(cytokines) = c("cytokine")
```

```{r plot CMTF model}
a = cbind(A, subjectMeta) %>% as_tibble() %>% arrange(Symptomatic) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1,fill=as.factor(Symptomatic))) + geom_bar(stat="identity") + theme(legend.position="bottom") + xlab("Subject index") + ylab("Component 1") + ggtitle("Subject mode (shared)")
b = cbind(B, cytokines) %>% as_tibble() %>% ggplot(aes(x=as.factor(cytokine),y=V1)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Cytokine") + ylab("") + ggtitle("Feature mode X (cytokines)")
c = cbind(C, time) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1,fill=as.factor(extraction))) + geom_bar(stat="identity") + theme(legend.position="bottom") + xlab("Visit") + ylab("") + ggtitle("Time mode")
d = cbind(D, taxonomy) %>% as_tibble() %>% arrange(KO) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1)) + geom_bar(stat="identity") + theme(legend.position="bottom") + xlab("Feature index") + ylab("") + ggtitle("Feature mode Y (func. microbiome)")

ggarrange(a,b,c,d, nrow=1)
```

```{r test subject mode}
AsubjectMeta = read.csv("./20241031_ACMTF_func/Athina_homogenized_subjectMeta.csv",header=FALSE) %>% as_tibble()
colnames(AsubjectMeta) = c("SubjectID", "symptomatic")

otherMeta = read.csv("./Data/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

cytokines_meta_data = read.csv("./input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

normalSubjectLoadings = cbind(A, AsubjectMeta) %>% as_tibble() %>% left_join(cytokines_meta_data %>% select(-Visit) %>% unique()) %>% left_join(otherMeta)

uncorrectedP = matrix(NA, nrow=1, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(V1) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V1) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "bonferroni"), nrow=1, ncol=4)
print(correctedP)
```

```{r also plot correlations}
a=normalSubjectLoadings %>% ggplot(aes(x=as.factor(Gender),y=V1)) + geom_boxplot() + stat_compare_means() + xlab("Gender") + ylab("Component 1") + ggtitle("Gender")
b=normalSubjectLoadings %>% ggplot(aes(x=Age,y=V1)) + geom_point() + xlab("Age") + ylab("Component 1") + ggtitle("Age")
c=normalSubjectLoadings %>% ggplot(aes(x=DMFT,y=V1)) + geom_point() + xlab("DMFT") + ylab("Component 1") + ggtitle("DMFT")
d=normalSubjectLoadings %>% ggplot(aes(x=as.factor(symptomatic),y=V1)) + geom_boxplot() + stat_compare_means() + xlab("Pain/NoPain") + ylab("Component 1") + ggtitle("Symptomatic")
ggarrange(a,b,c,d)
```

```{r interpretation microbiome}
D_annotated = cbind(D,taxonomy) %>% as_tibble() %>% mutate(V1 = -1*V1) %>% arrange(V1) %>% mutate(index=1:nrow(.))
                                                                                                  
#D_annotated %>% arrange(V1) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(y=as.factor(index),x=V1,label=KO)) + geom_bar(stat="identity") + xlab("Feature loadings") + ylab("Name") + scale_y_discrete(labels=D_annotated$KO)
```

# SetRank 

```{r alternative approach - setRank}
library(SetRank)
```

```{r make or load collection}
#options(mc.cores=8)
collection = readRDS("./setRankCollection.RDS")
#collection = buildSetCollection(inputForCollection, maxSetSize=750)
#saveRDS(collection, "./setRankCollection.RDS")
```

```{r preparing setRank input}
setRankInput = D_annotated$KO
```

```{r running setRank}
options(mc.cores=6)
network = setRankAnalysis(setRankInput, collection, use.ranks=TRUE, setPCutoff=1)
exportSingleResult(network, setRankInput, collection, "Athina_SetRank_result", outputPath="./20241031_ACMTF_func/")
```

```{r reimport}
pathwayResult = read.csv("./20241031_ACMTF_func/Athina_setRank_result_pathways.txt", sep="\t") %>% as_tibble()
pathwayResult %>% arrange(pSetRank, correctedPValue, adjustedPValue)
```