---
title: "ModelInterpretation"
author: "G.R. van der Ploeg"
date: "2024-04-17"
output: html_document
---

```{r import statement}
# parafac work
library(tidyverse)
library(ggpubr)
library(paramGUI)
library(pracma)
library(ggrepel)
library(scales)
library(parafac4microbiome)
```

```{r define all colours}
colours = hue_pal()(11)
print(colours)
```

```{r import the models}
importPARAFAC = function(path, prefix, mode="microbiome", numComponents=1){
  obj = list()
  obj$model = list()
  
  obj$model$A = read.csv(paste0(path,prefix,"_mode1.csv"), header=FALSE)
  obj$model$B = read.csv(paste0(path,prefix,"_mode2.csv"), header=FALSE)
  obj$model$C = read.csv(paste0(path,prefix,"_mode3.csv"), header=FALSE)
  obj$reconstructedData = read.csv(paste0(path,prefix,"_model.csv"), header=FALSE)
  obj$dataset$data = read.csv(paste0(path,prefix,"_input.csv"), header=FALSE)
  obj$dataset$mode1 = as.matrix(obj$model$A[,(numComponents+1):ncol(obj$model$A)])
  obj$dataset$mode2 = as.matrix(obj$model$B[,(numComponents+1):ncol(obj$model$B)])
  obj$dataset$mode3 = as.matrix(obj$model$C[,(numComponents+1):ncol(obj$model$C)])
  
  colnames(obj$dataset$mode1) = c("subject", "Case_control")
  colnames(obj$dataset$mode3) = c("Extraction")
  
  if(mode=="microbiome"){
    colnames(obj$dataset$mode2) = c("num", "zOTU", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
  }
  return(obj)
}

timepoints = c(-6, -3, 0, 1, 6, 13) # weeks before/after extraction

# Import the models
onlyCase = importPARAFAC("./20230913_run_onlyCase/PARAFAC models/", "Athina", mode="bla", numComponents=2)
onlyControl = importPARAFAC("./20230913_run_onlyControl/PARAFAC models/", "Athina", mode="bla", numComponents=3)
allSamples = importPARAFAC("./20230913_run_removedSubjects/PARAFAC models/", "Athina", mode="bla", numComponents=3)

colnames(onlyCase$dataset$mode1) = c("SubjectID", "Symptoms")
colnames(onlyCase$dataset$mode2) = c("cytokine")
colnames(onlyCase$dataset$mode3) = c("extraction")
onlyCase$dataset$mode3 = onlyCase$dataset$mode3 %>% as_tibble() %>% mutate(timepoint = timepoints)

colnames(onlyControl$dataset$mode1) = c("SubjectID", "control")
colnames(onlyControl$dataset$mode2) = c("cytokine")
colnames(onlyControl$dataset$mode3) = c("extraction")
onlyControl$dataset$mode3 = onlyControl$dataset$mode3 %>% as_tibble() %>% mutate(timepoint = timepoints)

colnames(allSamples$dataset$mode1) = c("SubjectID", "Symptoms")
colnames(allSamples$dataset$mode2) = c("cytokine")
colnames(allSamples$dataset$mode3) = c("extraction")
allSamples$dataset$mode3 = allSamples$dataset$mode3 %>% as_tibble() %>% mutate(timepoint = timepoints)
```

```{r load metadata}
fakeTimepoints = c(-9, -6, -3, 0, 1, 6, 13) # weeks, -9 is fake but there is a visit 0 somehow
subjectMeta = read.csv("./Data/export_txt_6_10_20_results_combi_merged.txt", sep="\t") %>% as_tibble()
subjectMeta = subjectMeta %>% mutate(timepoint = fakeTimepoints[Visit+1])

otherMeta = read.csv("./Data/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
```

```{r plot the onlyCase model}
a=cbind(onlyCase$model[[1]], onlyCase$dataset$mode1) %>% as_tibble() %>% arrange(Symptoms, SubjectID) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1,fill=as.factor(Symptoms))) + geom_bar(stat="identity")

b=cbind(onlyCase$model[[2]], onlyCase$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V1)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

c=cbind(onlyCase$model[[3]], onlyCase$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=timepoint,y=V1)) + geom_line()

d=cbind(onlyCase$model[[1]], onlyCase$dataset$mode1) %>% as_tibble() %>% arrange(Symptoms, SubjectID) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V2,fill=as.factor(Symptoms))) + geom_bar(stat="identity")

e=cbind(onlyCase$model[[2]], onlyCase$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V2)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

f=cbind(onlyCase$model[[3]], onlyCase$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=timepoint,y=V2)) + geom_line()

ggarrange(a,b,c,d,e,f)
```

```{r plot the onlyControl model}
a=cbind(onlyControl$model[[1]], onlyControl$dataset$mode1) %>% as_tibble() %>% arrange(SubjectID) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1)) + geom_bar(stat="identity") + xlab("") + ylab("Component 1")

b=cbind(onlyControl$model[[2]], onlyControl$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V1)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("")

c=cbind(onlyControl$model[[3]], onlyControl$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=1:nrow(.),y=V1)) + geom_point() + geom_line() + xlab("Visit") + ylab("")

d=cbind(onlyControl$model[[1]], onlyControl$dataset$mode1) %>% as_tibble() %>% arrange(SubjectID) %>% mutate(index=1:nrow(.)) %>% left_join(subjectMeta %>% select(SubjectID, Age) %>% unique()) %>% ggplot(aes(x=index,y=V2,fill=Age)) + geom_bar(stat="identity") + xlab("") + ylab("Component 2") + theme(legend.position="none")

e=cbind(onlyControl$model[[2]], onlyControl$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V2)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("")

f=cbind(onlyControl$model[[3]], onlyControl$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=1:nrow(.),y=V2)) + geom_point() + geom_line() + xlab("Visit") + ylab("")

g=cbind(onlyControl$model[[1]], onlyControl$dataset$mode1) %>% as_tibble() %>% arrange(SubjectID) %>% mutate(index=1:nrow(.)) %>% left_join(subjectMeta %>% select(SubjectID, Gender) %>% unique()) %>% ggplot(aes(x=index,y=V3,fill=as.factor(Gender))) + geom_bar(stat="identity") + xlab("Subject index") + ylab("Component 3") + theme(legend.position="none")

h=cbind(onlyControl$model[[2]], onlyControl$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V3)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Cytokine") + ylab("")

i=cbind(onlyControl$model[[3]], onlyControl$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=1:nrow(.),y=V3)) + geom_point() + geom_line() + xlab("Visit") + ylab("")

ggarrange(a,b,c,d,e,f,g,h,i)

# For legends
cbind(onlyControl$model[[1]], onlyControl$dataset$mode1) %>% as_tibble() %>% arrange(SubjectID) %>% mutate(index=1:nrow(.)) %>% left_join(subjectMeta %>% select(SubjectID, Age) %>% unique()) %>% ggplot(aes(x=index,y=V2,fill=Age)) + geom_bar(stat="identity") + xlab("") + ylab("Component 2")

cbind(onlyControl$model[[1]], onlyControl$dataset$mode1) %>% as_tibble() %>% arrange(SubjectID) %>% mutate(index=1:nrow(.)) %>% left_join(subjectMeta %>% select(SubjectID, Gender) %>% unique()) %>% ggplot(aes(x=index,y=V3,fill=as.factor(Gender))) + geom_bar(stat="identity") + xlab("Subject index") + ylab("Component 3")
```

```{r plot the full model}
a=cbind(allSamples$model[[1]], allSamples$dataset$mode1) %>% as_tibble() %>% arrange(Symptoms, SubjectID) %>% mutate(index=1:nrow(.), Subject = as.factor(Symptoms)) %>% ggplot(aes(x=index,y=V1,fill=Subject)) + geom_bar(stat="identity") + xlab("") + ylab("Component 1") + theme(legend.position = "top") + scale_fill_manual(name="Subject", labels=c("Asymptomatic case", "Control", "Symptomatic case"), values=colours[c(1,5,9)]) + guides(fill=guide_legend(nrow=3,byrow=TRUE))

b=cbind(allSamples$model[[2]], allSamples$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V1)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("")

c=cbind(allSamples$model[[3]], allSamples$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=1:nrow(.),y=V1)) + geom_point() + geom_line() + xlab("") + ylab("")

d=cbind(allSamples$model[[1]], allSamples$dataset$mode1) %>% as_tibble() %>% arrange(Symptoms,SubjectID) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V2,fill=as.factor(Symptoms))) + geom_bar(stat="identity") + xlab("") + ylab("Component 2") + theme(legend.position = "none") + scale_fill_manual(name="Subject", labels=c("Asymptomatic case", "Control", "Symptomatic case"), values=colours[c(1,5,9)])

e=cbind(allSamples$model[[2]], allSamples$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V2)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("") + ylab("")

f=cbind(allSamples$model[[3]], allSamples$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=1:nrow(.),y=V2)) + geom_point() + geom_line() + xlab("") + ylab("")

g=cbind(allSamples$model[[1]], allSamples$dataset$mode1) %>% as_tibble() %>% arrange(Symptoms,SubjectID) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V3,fill=as.factor(Symptoms))) + geom_bar(stat="identity") + xlab("Subject index") + ylab("Component 3") + theme(legend.position = "none") + scale_fill_manual(name="Subject", labels=c("Asymptomatic case", "Control", "Symptomatic case"), values=colours[c(1,5,9)])

h=cbind(allSamples$model[[2]], allSamples$dataset$mode2) %>% as_tibble() %>% ggplot(aes(x=cytokine, y=V3)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Cytokine") + ylab("")

i=cbind(allSamples$model[[3]], allSamples$dataset$mode3) %>% as_tibble() %>% ggplot(aes(x=1:nrow(.),y=V3)) + geom_point() + geom_line() + xlab("Visit") + ylab("")

ggarrange(a,b,c,d,e,f,g,h,i)
```

```{r plot the models}
# Plot the models
colourCols1 = c("Symptoms", "cytokine", "")
colourCols2 = c("", "cytokine", "")
legendTitles1 = c("Symptoms", "Cytokine", "")
legendTitles2 = c("Symptoms", "Cytokine", "")
xLabels = c("Subject index", "Feature index", "Time index")
legendColNums = c(1,5,1)
arrangeModes = c(TRUE, TRUE, FALSE)
continuousModes = c(FALSE,FALSE,TRUE)

varExp_case = round(multiway::sumsq(onlyCase$reconstructedData) / multiway::sumsq(onlyCase$dataset$data, na.rm=TRUE) * 100,2)
varExp_control = round(multiway::sumsq(onlyControl$reconstructedData) / multiway::sumsq(onlyControl$dataset$data, na.rm=TRUE) * 100,2)
varExp_all = round(multiway::sumsq(allSamples$reconstructedData) / multiway::sumsq(allSamples$dataset$data, na.rm=TRUE) * 100,2)

plotPARAFACmodel(list("A"=onlyCase$model[[1]], "B"=onlyCase$model[[2]], "C"=onlyCase$model[[3]]), onlyCase$dataset, 2, colourCols1, legendTitles1, xLabels, legendColNums, arrangeModes, continuousModes, overallTitle=paste0("Athina only case (", varExp_case, " %)"))
plotPARAFACmodel(list("A"=onlyControl$model[[1]], "B"=onlyControl$model[[2]], "C"=onlyControl$model[[3]]), onlyControl$dataset, 3, colourCols2, legendTitles2, xLabels, legendColNums, arrangeModes, continuousModes, overallTitle=paste0("Athina only control (", varExp_control, " %)"))
plotPARAFACmodel(list("A"=allSamples$model[[1]], "B"=allSamples$model[[2]], "C"=allSamples$model[[3]]), allSamples$dataset, 3, colourCols1, legendTitles1, xLabels, legendColNums, arrangeModes, continuousModes, overallTitle=paste0("Athina all samples (", varExp_all, " %)"))
```

```{r test metadata only case}
normalSubjectLoadings = cbind(onlyCase$model$A, onlyCase$dataset$mode1) %>% as_tibble() %>% left_join(subjectMeta %>% select(SubjectID, Gender, Age, DMFT, case_control) %>% unique()) %>% left_join(otherMeta)
transformedSubjectLoadings = parafac4microbiome::transformPARAFACloadings(onlyCase$model, 2, moreOutput=TRUE)$Ftilde %>% as_tibble() %>% mutate(SubjectID = rep(onlyCase$dataset$mode1$SubjectID, each=6), timepoint = rep(timepoints, nrow(onlyCase$model$A))) %>% left_join(subjectMeta)

uncorrectedP = matrix(NA, nrow=2, ncol=5)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V1) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V2) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V2) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$Age)$p.value
uncorrectedP[2,2] = cor.test(normalSubjectLoadings$V2, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[2,3] = cor.test(normalSubjectLoadings$V2, normalSubjectLoadings$DMFT)$p.value

# case_control
# everything is case

# pain-noPain
uncorrectedP[1,5] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V1) %>% pull())$p.value
uncorrectedP[2,5] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V2) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=2, ncol=5)
print(correctedP)

```

```{r test metadata only control}
normalSubjectLoadings = cbind(onlyControl$model$A, onlyControl$dataset$mode1) %>% as_tibble() %>% left_join(subjectMeta %>% select(SubjectID, Gender, Age, DMFT, case_control) %>% unique()) %>% left_join(otherMeta)
transformedSubjectLoadings = parafac4microbiome::transformPARAFACloadings(onlyControl$model, 2, moreOutput=TRUE)$Ftilde %>% as_tibble() %>% mutate(SubjectID = rep(onlyControl$dataset$mode1$SubjectID, each=6), timepoint = rep(timepoints, nrow(onlyControl$model$A))) %>% left_join(subjectMeta)

uncorrectedP = matrix(NA, nrow=3, ncol=5)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V1) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V2) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V2) %>% pull())$p.value
uncorrectedP[3,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V3) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V3) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$Age)$p.value
uncorrectedP[2,2] = cor.test(normalSubjectLoadings$V2, normalSubjectLoadings$Age)$p.value
uncorrectedP[3,2] = cor.test(normalSubjectLoadings$V3, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[2,3] = cor.test(normalSubjectLoadings$V2, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[3,3] = cor.test(normalSubjectLoadings$V3, normalSubjectLoadings$DMFT)$p.value

# case_control
# everything is case

# pain-noPain
# everything is control

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=3, ncol=5)
print(correctedP)

```

```{r test metadata only control}
normalSubjectLoadings = cbind(allSamples$model$A, allSamples$dataset$mode1) %>% as_tibble() %>% left_join(subjectMeta %>% select(SubjectID, Gender, Age, DMFT, case_control) %>% unique()) %>% left_join(otherMeta)
transformedSubjectLoadings = parafac4microbiome::transformPARAFACloadings(allSamples$model, 2, moreOutput=TRUE)$Ftilde %>% as_tibble() %>% mutate(SubjectID = rep(allSamples$dataset$mode1$SubjectID, each=6), timepoint = rep(timepoints, nrow(allSamples$model$A))) %>% left_join(subjectMeta)

uncorrectedP = matrix(NA, nrow=3, ncol=5)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V1) %>% pull())$p.value
uncorrectedP[2,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V2) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V2) %>% pull())$p.value
uncorrectedP[3,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender==1) %>% select(V3) %>% pull(), normalSubjectLoadings %>% filter(Gender==2) %>% select(V3) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$Age)$p.value
uncorrectedP[2,2] = cor.test(normalSubjectLoadings$V2, normalSubjectLoadings$Age)$p.value
uncorrectedP[3,2] = cor.test(normalSubjectLoadings$V3, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[2,3] = cor.test(normalSubjectLoadings$V2, normalSubjectLoadings$DMFT)$p.value
uncorrectedP[3,3] = cor.test(normalSubjectLoadings$V3, normalSubjectLoadings$DMFT)$p.value

# case_control
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(case_control==1) %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(case_control==2) %>% select(V1) %>% pull())$p.value
uncorrectedP[2,4] = wilcox.test(normalSubjectLoadings %>% filter(case_control==1) %>% select(V2) %>% pull(), normalSubjectLoadings %>% filter(case_control==2) %>% select(V2) %>% pull())$p.value
uncorrectedP[3,4] = wilcox.test(normalSubjectLoadings %>% filter(case_control==1) %>% select(V3) %>% pull(), normalSubjectLoadings %>% filter(case_control==2) %>% select(V3) %>% pull())$p.value

# pain-noPain
uncorrectedP[1,5] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V1) %>% pull())$p.value
uncorrectedP[2,5] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V2) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V2) %>% pull())$p.value
uncorrectedP[3,5] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V3) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V3) %>% pull())$p.value


print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=3, ncol=5)
print(correctedP)

```

```{r zooming in on specific cytokines}
cytokines_data = read.csv("./input_deduplicated_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_data) = c("VEGF", "CRP", "GM-CSF", "IL1alpha", "IL1beta", "IL4", "IL6", "IL8", "IL10", "IL12p70", "IL17A", "IFNgamma", "MIP1alpha", "OPG", "TNFalpha", "RANKL")

cytokines_meta_data = read.csv("./input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

df = cbind(cytokines_data, cytokines_meta_data) %>% as_tibble()

symnum.args <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf), symbols = c("****", "***", "**", "*", "ns"))

# only case comp 2 is age
cbind(onlyCase$model$B, onlyCase$dataset$mode2) %>% as_tibble() %>% arrange(desc(V2))

# Check relationship with age, this is consistent even after BH correction
a=df %>% ggplot(aes(x=Age,y=OPG)) + geom_point()
b=df %>% ggplot(aes(x=Age,y=VEGF)) + geom_point()
c=df %>% ggplot(aes(x=Age,y=CRP)) + geom_point()
d=df %>% ggplot(aes(x=Age,y=RANKL)) + geom_point()
ggarrange(a,b,c,d)

# Check relationship with gender, this disappears after BH correction
a = df %>% select(OPG, Gender, Visit) %>% pivot_longer(-c(Gender,Visit)) %>% ggplot(aes(x=as.factor(Visit),y=value,fill=as.factor(Gender))) + geom_boxplot() + stat_compare_means(method="wilcox", symnum.args = symnum.args) + xlab("Visit") + ylab("OPG")
```