---
title: "redoPackage"
output: html_document
date: "2024-04-18"
---

```{r libraries}
library(ggplot2)
library(parafac4microbiome)
```

```{r load the data}
cytokines_data = read.csv("./input_deduplicated_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_data) = c("VEGF", "CRP", "GM-CSF", "IL1alpha", "IL1beta", "IL4", "IL6", "IL8", "IL10", "IL12p70", "IL17A", "IFNgamma", "MIP1alpha", "OPG", "TNFalpha", "RANKL")

cytokines_meta_data = read.csv("./input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")
```

```{r put into a cube for processing}
I = 52
J = 16
K = 6
cube = array(0L, dim=c(I,J,K))

for(k in 1:K){
  temp = cbind(cytokines_data, cytokines_meta_data) %>% as_tibble()
  cube[,,k] = temp %>%
    filter(Visit == k) %>%
    right_join(cytokines_meta_data %>% select(SubjectID) %>% unique()) %>%
    arrange(SubjectID) %>%
    select(-all_of(colnames(cytokines_meta_data))) %>%
    as.matrix()
}

cube = sqrt(cube)
cube_cnt = multiwayCenter(cube, mode=1)
cube_cnt_scl = multiwayScale(cube_cnt, mode=2)

processedGeorgiou = list()
processedGeorgiou$data = cube_cnt_scl
processedGeorgiou$mode1 = cytokines_meta_data %>% select(-Visit) %>% unique() %>% arrange(SubjectID)
processedGeorgiou$mode2 = colnames(cytokines_data) %>% as_tibble()
processedGeorgiou$mode3 = cytokines_meta_data %>% select(Visit) %>% arrange(Visit) %>% unique() %>% mutate(extraction = c(rep("Before extraction",3), rep("After extraction",3)))
```

```{r inspect num components}
# Setup
# For computational purposes we deviate from the default settings
minNumComponents = 1
maxNumComponents = 3
numRepetitions = 50 # number of randomly initialized models
numFolds = 50 # number of jack-knifed models
ctol = 1e-8
maxit = 500
numCores = 12

colourCols = c("case_control", "value", "")
legendTitles = c("Case/Control", "Cytokine", "")
xLabels = c("Subject index", "Feature index", "Time index")
legendColNums = c(1,3,1)
arrangeModes = c(TRUE, TRUE, FALSE)
continuousModes = c(FALSE,FALSE,TRUE)

# Assess the metrics to determine the correct number of components
assessment = assessModelQuality(processedGeorgiou$data, minNumComponents, maxNumComponents, numRepetitions, ctol=ctol, maxit=maxit, numCores=numCores)

assessment$plots$overview

# modelStabilityCheck(processedGeorgiou, numComponents=1, numFolds=numFolds, considerGroups=TRUE,
#                                groupVariable="case_control", colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
#                                continuousModes, ctol=ctol, maxit=maxit, numCores=numCores)$plot
# modelStabilityCheck(processedGeorgiou, numComponents=2, numFolds=numFolds, considerGroups=TRUE,
#                                groupVariable="case_control", colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
#                                continuousModes, ctol=ctol, maxit=maxit, numCores=numCores)$plot
# modelStabilityCheck(processedGeorgiou, numComponents=3, numFolds=numFolds, considerGroups=TRUE,
#                                groupVariable="case_control", colourCols, legendTitles, xLabels, legendColNums, arrangeModes,
#                                continuousModes, ctol=ctol, maxit=maxit, numCores=numCores)$plot
# 
# assessment$plots$TCCoverall[[2]]
# assessment$plots$TCC[[2]]
```

```{r model selection}
numComponents = 1
modelChoice = which(assessment$metrics$varExp[,numComponents] == max(assessment$metrics$varExp[,numComponents]))
finalModel = assessment$models[[numComponents]][[modelChoice]]
```

```{r model}
plotPARAFACmodel(finalModel, processedGeorgiou, 1, colourCols, legendTitles, xLabels, legendColNums, arrangeModes, continuousModes,
  overallTitle = "Georgiou2024 PARAFAC model")
```

```{r tests}
otherMeta = read.csv("./Data/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

normalSubjectLoadings = cbind(finalModel$A, processedGeorgiou$mode1) %>% as_tibble() %>% left_join(otherMeta) %>% mutate(V1 = `finalModel$A`)
# transformedSubjectLoadings = parafac4microbiome::transformPARAFACloadings(finalModel, 2, moreOutput=TRUE)$Ftilde %>% as_tibble() %>% mutate(SubjectID = rep(processedGeorgiou$mode1$SubjectID, each=6), timepoint = rep(timepoints, nrow(finalModel$A))) %>% left_join(otherMeta)

uncorrectedP = matrix(NA, nrow=1, ncol=5)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(V1) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$DMFT)$p.value

# case_control
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(case_control=="case") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(case_control=="control") %>% select(V1) %>% pull())$p.value

# pain-noPain
uncorrectedP[1,5] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V1) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=1, ncol=5)
print(correctedP)

```

```{r back to the original data}
# case and control are separable, mainly by the RANKL concentration
temp = cbind(cytokines_data, cytokines_meta_data) %>% as_tibble() %>% select(RANKL,OPG,case_control,Visit,SubjectID,Age)

temp %>% ggplot(aes(x=as.factor(case_control),y=RANKL,fill=as.factor(case_control))) + geom_boxplot() + stat_compare_means()
temp %>% ggplot(aes(x=Age,y=RANKL)) + geom_point()

cor.test(temp$RANKL, temp$Age)

a=temp %>% select(RANKL,SubjectID,case_control,Visit) %>% group_by(case_control,Visit) %>% summarize(m=mean(RANKL),v=plotrix::std.error(RANKL)) %>% ggplot(aes(x=Visit,y=m,group=as.factor(case_control),col=as.factor(case_control))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=0.3,position=position_dodge()) + geom_point() + ggtitle("RANKL")

b=temp %>% select(OPG,SubjectID,case_control,Visit) %>% group_by(case_control,Visit) %>% summarize(m=mean(OPG,na.rm=TRUE),v=plotrix::std.error(OPG)) %>% ggplot(aes(x=Visit,y=m,group=as.factor(case_control),col=as.factor(case_control))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=0.3,position=position_dodge()) + geom_point() + ggtitle("OPG")

ggarrange(a,b,common.legend=TRUE)
```