---
title: "ACMTF_interpretation"
output: html_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(parafac4microbiome)
library(ggpubr)
library(ggrepel)
library(scales)
```

```{r define all colours}
colours = hue_pal()(11)
subject_group_cols = colours[c(1,5,9)]
symptom_group_cols = colours[c(1,9)]
phylum_cols = colours[-c(1,5,9)]
```

```{r load ACMTF model}
A = read.csv("./20241031_ACMTF/Athina_ACMTF_A.csv",header=FALSE) %>% as_tibble()
B = read.csv("./20241031_ACMTF/Athina_ACMTF_B.csv",header=FALSE) %>% as_tibble()
C = read.csv("./20241031_ACMTF/Athina_ACMTF_C.csv",header=FALSE) %>% as_tibble()
D = read.csv("./20241031_ACMTF/Athina_ACMTF_D.csv",header=FALSE) %>% as_tibble()

subjectMeta = read.csv("./20241031_ACMTF/Athina_homogenized_subjectMeta.csv",header=FALSE) %>% as_tibble()
colnames(subjectMeta) = c("subject", "Symptomatic")
taxonomy = read.csv("./20241031_ACMTF/Athina_taxonomy.csv",header=FALSE) %>% as_tibble()
colnames(taxonomy) = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "Zotu")
time = read.csv("./20241031_ACMTF/Athina_time.csv",header=FALSE) %>% as_tibble()
colnames(time) = c("extraction")
cytokines = read.csv("./20241031_ACMTF/Athina_cytokines.csv",header=FALSE) %>% as_tibble()
colnames(cytokines) = c("cytokine")

# Flip modes to match original model
A = -1 * A
B = -1 * B
D = -1 * D
```

```{r plot ACMTF model}
a = cbind(A, subjectMeta) %>% as_tibble() %>% arrange(Symptomatic, subject) %>% mutate(index=1:nrow(.),Subject=as.factor(Symptomatic)) %>% ggplot(aes(x=index,y=V1,fill=Subject)) + geom_bar(stat="identity") + theme(legend.position="top") + xlab("Subject index") + ylab("Component 1") + scale_fill_manual(name="Subject", labels=c("Asymptomatic case", "Symptomatic case"), values=symptom_group_cols) + guides(fill=guide_legend(nrow=2,byrow=TRUE)) + theme(legend.position="none")

b = cbind(B, cytokines) %>% as_tibble() %>% ggplot(aes(x=as.factor(cytokine),y=V1)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Cytokine") + ylab("")
c = cbind(C, time) %>% as_tibble() %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=V1)) + geom_point() + geom_line() + theme(legend.position="bottom") + xlab("Visit") + ylab("")
d = cbind(D, taxonomy) %>% as_tibble() %>% arrange(Phylum,Class,Order,Family,Genus,Species,Zotu) %>% mutate(index=1:nrow(.), Phylum=as.factor(str_split_fixed(Phylum, "__", 2)[,2])) %>% ggplot(aes(x=index,y=V1,fill=Phylum)) + geom_bar(stat="identity") + theme(legend.position="top") + xlab("Feature index") + ylab("") + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Fusobacteria", "Proteobacteria", "Saccharibacteria (TM7)", "Spirochaetes", "Synergistetes"), values=phylum_cols) + guides(fill=guide_legend(nrow=8,byrow=TRUE)) + theme(legend.position="none")

ggarrange(a,b,c,d, nrow=1)
ggarrange(a,b,c, nrow=1)
```

```{r test subject mode}
AsubjectMeta = read.csv("./20241031_ACMTF/Athina_homogenized_subjectMeta.csv",header=FALSE) %>% as_tibble()
colnames(AsubjectMeta) = c("SubjectID", "symptomatic")

otherMeta = read.csv("./Data/Root_meta_data_parafac.txt", sep="\t") %>% as_tibble() %>% select(-Gender)
timepoints = c(-6, -3, 0, 1, 6, 13)

cytokines_meta_data = read.csv("./input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

normalSubjectLoadings = cbind(A, AsubjectMeta) %>% as_tibble() %>% left_join(cytokines_meta_data %>% select(-Visit) %>% unique()) %>% left_join(otherMeta)

uncorrectedP = matrix(NA, nrow=1, ncol=4)

# Gender
uncorrectedP[1,1] = wilcox.test(normalSubjectLoadings %>% filter(Gender=="M") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(Gender=="F") %>% select(V1) %>% pull())$p.value

# Age
uncorrectedP[1,2] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$Age)$p.value

# DMFT
uncorrectedP[1,3] = cor.test(normalSubjectLoadings$V1, normalSubjectLoadings$DMFT)$p.value

# pain-noPain
uncorrectedP[1,4] = wilcox.test(normalSubjectLoadings %>% filter(PainS_NopainA=="S") %>% select(V1) %>% pull(), normalSubjectLoadings %>% filter(PainS_NopainA=="A") %>% select(V1) %>% pull())$p.value

print(uncorrectedP)
correctedP = matrix(p.adjust(uncorrectedP, "bonferroni"), nrow=1, ncol=4)
print(correctedP)
```

```{r also plot correlations}
a=normalSubjectLoadings %>% ggplot(aes(x=as.factor(Gender),y=V1)) + geom_boxplot() + stat_compare_means() + xlab("Gender") + ylab("Component 1") + ggtitle("Gender")
b=normalSubjectLoadings %>% ggplot(aes(x=Age,y=V1)) + geom_point() + xlab("Age") + ylab("Component 1") + ggtitle("Age")
c=normalSubjectLoadings %>% ggplot(aes(x=DMFT,y=V1)) + geom_point() + xlab("DMFT") + ylab("Component 1") + ggtitle("DMFT")
d=normalSubjectLoadings %>% ggplot(aes(x=as.factor(symptomatic),y=V1)) + geom_boxplot() + stat_compare_means() + xlab("Pain/NoPain") + ylab("Component 1") + ggtitle("Symptomatic")
ggarrange(a,b,c,d)
```

```{r interpretation microbiome}
threshold = 0.075

D_annotated = cbind(D,taxonomy) %>% as_tibble() %>% mutate(V1 = V1) %>% filter(abs(V1) >= threshold) %>% arrange(V1) %>% mutate(newGenus = str_split_fixed(Genus,"g__",2)[,2], newSpecies = str_split_fixed(Species,"s__",2)[,2])
D_annotated[D_annotated$newSpecies == "","newSpecies"] = "sp."
D_annotated[grepl("taxon", D_annotated$newSpecies), "newSpecies"] = "sp."
D_annotated = D_annotated %>% mutate(name = paste0(newGenus, " ", newSpecies), Phylum = as.factor(str_split_fixed(Phylum, "__", 2)[,2]))
D_annotated[59,"name"] = "Streptococcus dentisani/infantis/mitis/oralis"
D_annotated[D_annotated$name == " sp.","name"] = "Unknown"

#D_annotated = D_annotated %>% mutate(name = paste0(newGenus, " ", newSpecies))# %>% mutate(name = paste0(Zotu, " ", name))

D_annotated %>% mutate(index=1:nrow(.)) %>% ggplot(aes(y=as.factor(index),x=V1,fill=Phylum,label=name)) + geom_bar(stat="identity") + xlab("Feature loadings") + ylab("Name") + scale_y_discrete(labels=D_annotated$name) + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Fusobacteria", "Proteobacteria", "Spirochaetes", "Synergistetes"), values=phylum_cols[-6]) + guides(fill=guide_legend(nrow=8,byrow=TRUE)) + theme(legend.position="none")

D_annotated %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=as.factor(index),y=V1,fill=Phylum,label=name)) + geom_bar(stat="identity") + xlab("Name") + ylab("Feature loadings") + scale_x_discrete(labels=D_annotated$name) + scale_fill_manual(name="Phylum", labels=c("Actinobacteria", "Bacteroidetes", "Firmicutes", "Fusobacteria", "Proteobacteria", "Spirochaetes", "Synergistetes"), values=phylum_cols[-6]) + guides(fill=guide_legend(nrow=8,byrow=TRUE)) + theme(legend.position="none", text=element_text(size=12), axis.text.x = element_text(angle=45, hjust=1, face="italic", size=8))
```

```{r interpretation cytokines}
cytokines_data = read.csv("./input_deduplicated_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_data) = c("VEGF", "CRP", "GM-CSF", "IL1alpha", "IL1beta", "IL4", "IL6", "IL8", "IL10", "IL12p70", "IL17A", "IFNgamma", "MIP1alpha", "OPG", "TNFalpha", "RANKL")

cytokines_meta_data = read.csv("./input_deduplicated_metadata_RvdP.csv", sep=" ", header=FALSE) %>% as_tibble()
colnames(cytokines_meta_data) = c("SubjectID", "Visit", "Gender", "Age", "Pain_noPain", "case_control")

df = cbind(cytokines_data, cytokines_meta_data %>% select(SubjectID,Visit)) %>% as_tibble() %>% left_join(otherMeta %>% select(PainS_NopainA, SubjectID)) %>% filter(PainS_NopainA != "NA") # remove controls

a=df %>% select(VEGF,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(VEGF,na.rm=TRUE),v=plotrix::std.error(VEGF,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("VEGF") + theme(legend.position="top",text=element_text(size=16))

b=df %>% select(CRP,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(CRP,na.rm=TRUE),v=plotrix::std.error(CRP,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("CRP") + theme(legend.position="top",text=element_text(size=16))

c=df %>% select(`GM-CSF`,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(`GM-CSF`,na.rm=TRUE),v=plotrix::std.error(`GM-CSF`,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("GM-CSF") + theme(legend.position="top",text=element_text(size=16))

d=df %>% select(IL1alpha,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL1alpha,na.rm=TRUE),v=plotrix::std.error(IL1alpha,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL1alpha") + theme(legend.position="top",text=element_text(size=16))

e=df %>% select(IL1beta,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL1beta,na.rm=TRUE),v=plotrix::std.error(IL1beta,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL1beta") + theme(legend.position="top",text=element_text(size=16))

f=df %>% select(IL4,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL4,na.rm=TRUE),v=plotrix::std.error(IL4,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL4") + theme(legend.position="top",text=element_text(size=16))

g=df %>% select(IL6,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL6,na.rm=TRUE),v=plotrix::std.error(IL6,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL6") + theme(legend.position="top",text=element_text(size=16))

h=df %>% select(IL8,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL8,na.rm=TRUE),v=plotrix::std.error(IL8,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL8") + theme(legend.position="top",text=element_text(size=16))

i=df %>% select(IL10,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL10,na.rm=TRUE),v=plotrix::std.error(IL10,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL10") + theme(legend.position="top",text=element_text(size=16))

j=df %>% select(IL12p70,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL12p70,na.rm=TRUE),v=plotrix::std.error(IL12p70,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL12p70") + theme(legend.position="top",text=element_text(size=16))

k=df %>% select(IL17A,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IL17A,na.rm=TRUE),v=plotrix::std.error(IL17A,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IL17A") + theme(legend.position="top",text=element_text(size=16))

l=df %>% select(IFNgamma,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(IFNgamma,na.rm=TRUE),v=plotrix::std.error(IFNgamma,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("IFNgamma") + theme(legend.position="top",text=element_text(size=16))

m=df %>% select(MIP1alpha,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(MIP1alpha,na.rm=TRUE),v=plotrix::std.error(MIP1alpha,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("MIP1alpha") + theme(legend.position="top",text=element_text(size=16))

n=df %>% select(OPG,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(OPG,na.rm=TRUE),v=plotrix::std.error(OPG,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("OPG") + theme(legend.position="top",text=element_text(size=16))

o=df %>% select(TNFalpha,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(TNFalpha,na.rm=TRUE),v=plotrix::std.error(TNFalpha,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("TNFalpha") + theme(legend.position="top",text=element_text(size=16))

p=df %>% select(RANKL,Visit,SubjectID,PainS_NopainA) %>% group_by(Visit,PainS_NopainA) %>% summarize(m=mean(RANKL,na.rm=TRUE),v=plotrix::std.error(RANKL,na.rm=TRUE)) %>% ggplot(aes(x=as.factor(Visit),y=m,col=as.factor(PainS_NopainA),group=as.factor(PainS_NopainA))) + geom_line() + geom_errorbar(aes(ymin=m-v,ymax=m+v),width=.2) + xlab("Visit") + ylab("RANKL") + theme(legend.position="top",text=element_text(size=16))

ggarrange(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,common.legend=TRUE)
```

```{r permutation test of cytokines}
permutationTest = function(df, featureName, visitNumber, numPermutations){
  df.numeric = df %>% filter(Visit==visitNumber)
  df.meta = df.numeric %>% select(SubjectID)

  refinedDF = df.numeric %>% select(all_of(c(featureName,"SubjectID","PainS_NopainA")))

  dfA = refinedDF %>% filter(PainS_NopainA=="A") %>% select(featureName) %>% pull()
  dfB = refinedDF %>% filter(PainS_NopainA=="S") %>% select(featureName) %>% pull()
  #realResult = wilcox.test(dfA, dfB)$p.value
  realResult = mean(dfA,na.rm=TRUE) - mean(dfB,na.rm=TRUE)

  # Permutations
  set.seed(1)
  permutedResults = 1:numPermutations
  for(i in 1:numPermutations){
    dfA = refinedDF %>% mutate(PainS_NopainA = sample(PainS_NopainA)) %>% filter(PainS_NopainA=="A") %>% select(featureName) %>% pull()
    dfB = refinedDF %>% mutate(PainS_NopainA = sample(PainS_NopainA)) %>% filter(PainS_NopainA=="S") %>% select(featureName) %>% pull()
    #permutedResults[i] = wilcox.test(dfA, dfB)$p.value
    permutedResults[i] = mean(dfA,na.rm=TRUE) - mean(dfB,na.rm=TRUE)
  }

  Zscore = abs(realResult - mean(permutedResults,na.rm=TRUE)) / sd(permutedResults,na.rm=TRUE)

  if (realResult < 0){
    pvalue = sum(permutedResults <= realResult) / numPermutations
  }
  else{
    pvalue = sum(permutedResults >= realResult) / numPermutations
  }
  
  if(!is.na(pvalue) & pvalue == 0){
    pvalue = 1/numPermutations
  }


  return(list(realResult, permutedResults, mean(permutedResults), median(permutedResults), sd(permutedResults), Zscore, pvalue))
}

uncorrectedP = matrix(NA, nrow=16, ncol=6)
featureNames = c("VEGF", "CRP", "GM-CSF", "IL1alpha", "IL1beta", "IL4", "IL6", "IL8", "IL10", "IL12p70", "IL17A", "IFNgamma", "MIP1alpha", "OPG", "TNFalpha", "RANKL")

for(visit in 1:6){
  for(i in 1:length(featureNames)){
    uncorrectedP[i,visit] = permutationTest(df, featureNames[i], visit, 999)[[7]]
  }
}

uncorrectedP
correctedP = matrix(p.adjust(uncorrectedP, "BH"), nrow=16, ncol=6)
correctedP
```