---
title: "FuncMicrobiome"
author: "G.R. van der Ploeg"
date: "2024-07-12"
output: html_document
---

```{r setup}
library(tidyverse)
library(ggpubr)
```

```{r load data}
df = read.csv("microb_func_preprocessed.csv", header=FALSE) %>% as_tibble()
sampleMeta = read.csv("microb_func_preprocessed_meta.csv", header=FALSE) %>% as_tibble()
featureMeta = read.csv("microb_func_preprocessed_features.csv", header=FALSE) %>% as_tibble()
```

```{r pca}
pca_res = prcomp(df, scale. = FALSE)

cbind(pca_res$x, sampleMeta) %>% as_tibble() %>% ggplot(aes(x=as.factor(V4),y=PC1)) + geom_boxplot() + stat_compare_means()
cbind(pca_res$rotation, featureMeta) %>% as_tibble() %>% select(PC1,V1,V2) %>% arrange(PC1)
cbind(pca_res$rotation, featureMeta) %>% as_tibble() %>% select(PC1,V1,V2) %>% arrange(desc(PC1))
```

```{r Import KO mappings}
# Mapping of KO K-number to pathways
KO2pathway = read.csv("./kegg_ko2pathway.txt", sep="\t", header=FALSE) %>% as_tibble()
colnames(KO2pathway) = c("pathway", "KO")
dummy = unlist(strsplit(KO2pathway["KO"] %>% pull, "ko:"))
KO2pathway["KO"] = dummy[dummy != ""]

# Mapping of pathway ID to pathway name
pathway2name = read.csv("./kegg_pathwayNames.txt", sep="\t", header=FALSE) %>% as_tibble()
colnames(pathway2name) = c("pathway", "name")
#pathway2name2 = pathway2name
#pathway2name2$pathway = str_replace(pathway2name$pathway, "map", "ko")
```

```{r create a unified list of varexp and congruence per model}
featureMetrics = cbind(pca_res$rotation, featureMeta) %>% as_tibble() %>% select(PC1, V1, V2) %>% arrange(PC1)
```

```{r alternative approach - setRank}
library(SetRank)

KOdescriptions = featureMeta
colnames(KOdescriptions) = c("geneID", "description")

KO2pathway_integrated = KO2pathway
colnames(KO2pathway_integrated) = c("pathway", "geneID")
KO2pathway_integrated = KO2pathway_integrated %>% mutate(pathway = str_split_fixed(KO2pathway_integrated$pathway, "path:", 2)[,2])

reduced_pathway2name = pathway2name[1:299,]
partA = KO2pathway_integrated %>% left_join(reduced_pathway2name) %>% filter(name != "NA") %>% left_join(KOdescriptions) %>% mutate(termID=pathway,termName=name,dbName="KEGG") %>% select(termID, geneID, termName, dbName, description)

inputForCollection =  partA %>% arrange(termID) %>% filter(!termName %in% c("Primary bile acid biosynthesis", "Aminoacyl-tRNA biosynthesis", "Photosynthesis - antenna proteins", "Brassinosteroid biosynthesis", "Zeatin biosynthesis", "Flavonoid biosynthesis", "Isoflavonoid biosynthesis", "Biosynthesis of plant hormones", "Signaling pathways regulating pluripotency of stem cells", "Platelet activation", "Renin-angiotensin system", "Natural killer cell mediated cytotoxicity", "B cell receptor signaling pathway", "Fc gamma R-mediated phagocytosis", "Leukocyte transendothelial migration", "Circadian rhythm", "Circadian rhythm - plant", "Glutamatergic synapse", "Serotonergic synapse", "Dopaminergic synapse", "Olfactory transduction", "Phototransduction", "Insulin signaling pathway", "Progesterone-mediated oocyte maturation", "Thyroid hormone synthesis", "Type II diabetes mellitus", "Type I diabetes mellitus", "Collecting duct acid secretion", "Gastric acid secretion", "Alzheimer's disease", "Amyotrophic lateral sclerosis (ALS)", "Prion diseases", "Salmonella infection", "Legionellosis", "Chagas disease (American trypanosomiasis)", "Malaria", "Amoebiasis", "Tuberculosis", "Hepatitis B", "Influenza A", "Herpes simplex infection", "Pathways in cancer", "Viral carcinogenesis", "Proteoglycans in cancer", "Colorectal cancer", "Pancreatic cancer", "Glioma", "Thyroid cancer", "Melanoma", "Chronic myeloid leukemia", "Small cell lung cancer", "Central carbon metabolism in cancer", "Asthma", "Inflammatory bowel disease (IBD)", "Rheumatoid arthritis", "Graft-versus-host disease", "Hypertrophic cardiomyopathy (HCM)", "Dilated cardiomyopathy", "Biosynthesis of plant secondary metabolites", "Hypnotics", "Antiarrhythmic drugs", "Anti-HIV agents", "Photosynthesis", "Ribosome biogenesis in eukaryotes", "MAPK signaling pathway - yeast", "MAPK signaling pathway - fly", "Cell cycle - yeast", "Meiosis - yeast", "p53 signaling pathway", "Cardiac muscle contraction", "Vascular smooth muscle contraction", "Axon guidance", "Osteoclast differentiation", "Hippo signaling pathway - fly", "Antigen processing and presentation", "Plant-pathogen interaction", "Hematopoietic cell lineage", "T cell receptor signaling pathway", "Intestinal immune network for IgA production", "Circadian rhythm - fly", "Circadian entrainment", "Synaptic vesicle cycle", "Cholinergic synapse", "GABAergic synapse", "Long-term depression", "Phototransduction - fly", "Ovarian steroidogenesis", "Estrogen signaling pathway", "Prolactin signaling pathway", "Regulation of lipolysis in adipocytes", "Non-alcoholic fatty liver disease (NAFLD)", "Maturity onset diabetes of the young", "Pancreatic secretion", "Bile secretion", "Parkinson's disease", "Huntington's disease", "Epithelial cell signaling in Helicobacter pylori infection", "Shigellosis", "Pertussis", "Leishmaniasis", "African trypanosomiasis", "Toxoplasmosis", "Hepatitis C", "Measles", "Epstein-Barr virus infection", "Transcriptional misregulation in cancer", "Chemical carcinogenesis", "MicroRNAs in cancer", "Renal cell carcinoma", "Endometrial cancer", "Prostate cancer", "Basal cell carcinoma", "Bladder cancer", "Acute myeloid leukemia", "Non-small cell lung cancer", "Choline metabolism in cancer", "Autoimmune thyroid disease", "Allograft rejection", "Arrhythmogenic right ventricular cardiomyopathy (ARVC)", "Viral myocarditis", "Biosynthesis of plant hormones", "Anticonvulsants", "Opioid analgesics", "HIV protease inhibitors")) %>% as.data.frame()

inputForCollection %>% as_tibble() %>% select(termID) %>% pull() %>% table() %>% as_tibble() %>% mutate(pathway=unique(inputForCollection$termName)) %>% left_join(pathway2name) %>% arrange(desc(n))
inputForCollection %>% as_tibble() %>% select(termID) %>% pull() %>% table() %>% as_tibble() %>% ggplot(aes(x=n)) + geom_histogram(bins=100) + geom_vline(xintercept=750, col="red")
inputForCollection %>% as_tibble() %>% select(termID) %>% pull() %>% table() %>% as_tibble() %>% filter(n<=750) %>% ggplot(aes(x=n)) + geom_histogram()
```

```{r make or load collection}
options(mc.cores=8)
#collection = readRDS("./setRankCollection.RDS")
collection = buildSetCollection(inputForCollection, maxSetSize=750)
saveRDS(collection, "./setRankCollection.RDS")
```

```{r preparing setRank input}
setRankInput = featureMetrics %>% mutate(geneID=V1) %>% arrange(PC1) %>% select(geneID) %>% pull
```

```{r running setRank}
network = setRankAnalysis(setRankInput, collection, use.ranks=TRUE, setPCutoff=1)
exportSingleResult(network, setRankInput, collection, "Athina_SetRank_result", outputPath="./20240712_microb_big/")
```