---
title: "Tax4Fun2_interpretation"
output: html_document
date: "2024-08-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

```{r load the relevant data}
# ACMTF model
A = read.csv("./20241031_ACMTF_func/Athina_ACMTF_A.csv", header=FALSE) %>% as_tibble()
colnames(A) = c("Component_1")
B = read.csv("./20241031_ACMTF_func/Athina_ACMTF_B.csv", header=FALSE) %>% as_tibble()
colnames(B) = c("Component_1")
C = read.csv("./20241031_ACMTF_func/Athina_ACMTF_C.csv", header=FALSE) %>% as_tibble()
colnames(C) = c("Component_1")
D = read.csv("./20241031_ACMTF_func/Athina_ACMTF_D.csv", header=FALSE) %>% as_tibble()
colnames(D) = c("Component_1")

subjectMeta = read.csv("./20241031_ACMTF_func/Athina_homogenized_subjectMeta.csv", header=FALSE) %>% as_tibble()
colnames(subjectMeta) = c("subject", "symptomatic")
KOmeta = read.csv("./20241031_ACMTF_func/Athina_taxonomy.csv", header=FALSE) %>% as_tibble()
colnames(KOmeta) = c("ko", "description")
time = read.csv("./20241031_ACMTF_func/Athina_time.csv", header=FALSE) %>% as_tibble() %>% mutate(visit=1:6)
colnames(time) = c("extraction", "visit")
cytokines = read.csv("./20241031_ACMTF_func/Athina_cytokines.csv", header=FALSE) %>% as_tibble()
colnames(cytokines) = c("cytokine")

A = cbind(A, subjectMeta) %>% as_tibble()
B = cbind(B, cytokines) %>% as_tibble()
C = cbind(C, time) %>% as_tibble()
D = cbind(D, KOmeta) %>% as_tibble()

# Tax4Fun2 output
Tax4Fun2_functional_prediction = read.csv("20240724_Tax4Fun2_output/Athina_Tax4Fun2_rarefied_6k/functional_prediction.txt", header=TRUE, sep="\t") %>% as_tibble()
Tax4Fun2_KOs_per_ASV = read.csv("20240724_Tax4Fun2_output/Athina_Tax4Fun2_rarefied_6k/KOs_per_ASV.txt", header=TRUE, sep="\t") %>% as_tibble()
Tax4Fun2_pathway_per_ASV = read.csv("20240724_Tax4Fun2_output/Athina_Tax4Fun2_rarefied_6k/pathway_per_ASV.txt", header=TRUE, sep="\t") %>% as_tibble()
Tax4Fun2_pathway_prediction = read.csv("20240724_Tax4Fun2_output/Athina_Tax4Fun2_rarefied_6k/pathway_prediction.txt", header=TRUE, sep="\t") %>% as_tibble()

# SetRank output
setRank_membership = read.csv("./20241031_ACMTF_func/Athina_SetRank_result_membership.txt", header=TRUE, sep="\t") %>% as_tibble()
setRank_pathways = read.csv("./20241031_ACMTF_func/Athina_SetRank_result_pathways.txt", header=TRUE, sep="\t") %>% as_tibble()

# Mappings
ko2pathway = read.csv("kegg_ko2pathway.txt", sep="\t", header=FALSE) %>% as_tibble() %>% mutate(V1 = str_replace(V1, "path:", ""))
colnames(ko2pathway) = c("pathway", "ko")
pathwayNames = read.csv("kegg_pathwayNames.txt", sep="\t", header=FALSE) %>% as_tibble()
colnames(pathwayNames) = c("pathway", "description")

# Flip modes for consistency and easier interpretation
#A$Component_1 = -1 * A$Component_1
#C$Component_1 = -1 * C$Component_1
#D$Component_1 = -1 * D$Component_1
```

```{r visualize the acmtf model}
a = A %>% arrange(symptomatic) %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1,fill=as.factor(symptomatic))) + geom_bar(stat="identity")
b = B %>% ggplot(aes(x=as.factor(cytokine),y=Component_1)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
c = C %>% ggplot(aes(x=visit,y=Component_1)) + geom_bar(stat="identity")
d = D %>% mutate(index=1:nrow(.)) %>% ggplot(aes(x=index,y=Component_1)) + geom_bar(stat="identity")

ggarrange(a,b,c,d)

A %>% ggplot(aes(x=as.factor(symptomatic),y=Component_1)) + geom_boxplot() + stat_compare_means()
```
```{r check loadings with tax4fun2 output}
checkKO = function(KOname){
  df = Tax4Fun2_functional_prediction %>% filter(KO == KOname) %>% select(-KO, -description)
  subjectNames = colnames(df)
  plottableData = df %>% t() %>% as.numeric() %>% as_tibble() %>% mutate(subject = subjectNames) %>% mutate(subject = str_replace(subject, "A11.", "A11-")) %>% filter(!subject %in% c("A11-18", "A11-3", "A11-8.36", "A11-10.17", "A11-15.17")) %>% mutate(subject = str_replace(subject, "[.]..", "")) %>% left_join(subjectMeta)
    
  plottableData %>% ggplot(aes(x=as.factor(symptomatic),y=value)) + geom_boxplot() + stat_compare_means() + ylab(KOname)
}

KOlist = D %>% arrange(desc(Component_1)) %>% select(ko) %>% pull()
plotlist = list()
for(i in 1:25){
  KOname = KOlist[i]
  plotlist[[i]] = checkKO(KOname)
}

ggarrange(plotlist=plotlist)
```

```{r check important KOs for some Zotus}
set.seed(123)

plotZotu = function(Zotu){
  df = Tax4Fun2_KOs_per_ASV %>% filter(ASV == Zotu) %>% select(-ASV)
  df %>% t() %>% as_tibble() %>% mutate(ko=colnames(df)) %>% left_join(D) %>% filter(Component_1 != "NA", description != "NA") %>% ggplot(aes(x=V1,y=Component_1)) + geom_point() + xlab("Tax4Fun2 prediction") + ylab("CMTF loading") + ggtitle(Zotu)
}

importantZotus = c("Zotu1", "Zotu3", "Zotu4", "Zotu5", "Zotu7", "Zotu8", "Zotu9")
unimportantZotus = sample(Tax4Fun2_KOs_per_ASV$ASV, 18)
Zotus = c(importantZotus, unimportantZotus)

plotlist = list()
for(i in 1:25){
  plotlist[[i]] = plotZotu(Zotus[i])
}

ggarrange(plotlist=plotlist)

Tax4Fun2_KOs_per_ASV %>% filter(ASV %in% Zotus) %>% pivot_longer(-ASV) %>% mutate(ko=name) %>% left_join(D) %>% filter(Component_1 != "NA", "description" != "NA", value > 0) %>% ggplot(aes(x=as.factor(ASV),y=Component_1)) + geom_boxplot()
```

```{r check for Tax4fun2 predicted pathways}
#importantPathways = setRank_pathways %>% arrange(pSetRank, correctedPValue, adjustedPValue) %>% select(name) %>% pull()
#importantPathways = importantPathways[1:20] # top 10

importantPathways = setRank_pathways %>% filter(pSetRank <= 0.05 & correctedPValue <= 0.05 & adjustedPValue <= 0.05) %>% arrange(correctedPValue) %>% select(name) %>% pull()

Tax4Fun2_pathway_per_ASV %>% pivot_longer(-X) %>% mutate(pathway = str_replace(name, "ko", "map"), Zotu = X) %>% filter(pathway %in% importantPathways) %>% mutate(important = Zotu %in% importantZotus) %>% left_join(pathwayNames) %>% ggplot(aes(x=as.factor(important),y=value)) + facet_wrap(~as.factor(description)) + geom_boxplot() + stat_compare_means()

Tax4Fun2_pathway_per_ASV %>% mutate(important = X %in% importantZotus) %>% pivot_longer(-c(X, important)) %>% ggplot(aes(x=as.factor(important),y=value)) + geom_boxplot()

Tax4Fun2_pathway_prediction %>% select(-level1, -level2, -level3) %>% mutate(pathway = str_replace(pathway, "ko", "map")) %>% filter(pathway %in% importantPathways) %>% pivot_longer(-pathway) %>% left_join(pathwayNames) %>% mutate(subject = name) %>% mutate(subject = str_replace(subject, "A11.", "A11-")) %>% filter(!subject %in% c("A11-10.17", "A11-15.25", "A11-8.36")) %>% mutate(subject = str_replace(subject, "[.]..", "")) %>% left_join(subjectMeta) %>% ggplot(aes(x=as.factor(symptomatic),y=value)) + facet_wrap(~description) + geom_boxplot() + stat_compare_means()
```

```{r make pathway plots}
library(pathview)

# Calculate varExp per ko to use for coloring the pathview plot
# inputData = read.csv("./20240724_ACMTF_func/CMTF_input_data_microb.csv", header=FALSE) %>% as_tibble()
# predictedData = tcrossprod(A$Component_1, D$Component_1) %>% as_tibble()
# varExps = (apply(predictedData, 2, function(x){sum(x^2)}) / 23) * 100


for(i in 1:length(importantPathways)){
  pathwayName = importantPathways[i]
  pathwayID = str_replace(pathwayName, "map", "ko")
  pathwayKOs = ko2pathway %>% filter(pathway == pathwayName) %>% mutate(ko=str_replace(ko, "ko:", ""))
  df = D %>% filter(ko %in% pathwayKOs$ko) %>% mutate(normalizedLoadings = Component_1 / max(Component_1))
  row.names(df) = df$ko
  
  pathview_input = as.matrix(df$normalizedLoadings)
  row.names(pathview_input) = df$ko
  
  try(pathview(gene.data=pathview_input, pathway.id=pathwayID, species="ko", low=list(gene="red"), mid=list(gene="gray"), high=list(gene="green")))
}

  
# makePathviewImage = function(model, pathwayName, filename, path){
#   pathwayKO = pathway2name2 %>% filter(name == pathwayName) %>% select(pathway) %>% pull %>% strsplit("path:ko")
#   pathwayKO = pathwayKO[[1]][2]
#   
#   func_modeled_data = funcModel[[6]]
#   func_input_data = funcModel[[7]]
#   func_result = (apply(func_modeled_data^2, 2, sum) / apply(func_input_data^2, 2, sum)) %>% as_tibble() %>% mutate(KO=funcModel[[2]]$KO)
#   func_totalVarExp = sum(func_modeled_data^2) / sum(func_input_data^2)
# 
#   functional_pathview_data = func_result %>% select(value) %>% pull
#   functional_pathview_data = functional_pathview_data - func_totalVarExp
# 
#   #rescale_to_min1_max1 <- function(x){   (x - min(x))/(max(x)-min(x)) * (newMax - newMin) + newMin}
#   rescale_to_min1_max1 <- function(x){   (x - min(x))/(max(x)-min(x)) * (1 - -1) + -1}
#   functional_pathview_data = rescale_to_min1_max1(functional_pathview_data) # rescale to [-1,1]
#   names(functional_pathview_data) = func_result %>% select(KO) %>% pull
# 
#   modeled_data = metabolomicsModel[[6]]
#   input_data = metabolomicsModel[[7]]
#   result = (apply(modeled_data^2, 2, sum) / apply(input_data^2, 2, sum)) %>% as_tibble() %>% mutate(BIOCHEMICAL=metabolomicsModel[[2]]$BIOCHEMICAL) %>% left_join(metabolomics.features %>% select(BIOCHEMICAL, KEGG)) %>% filter(KEGG != "NA")
#   totalVarExp = sum(modeled_data^2) / sum(input_data^2)
# 
#   compound_pathview = result %>% select(value) %>% pull
#   compound_pathview = compound_pathview - totalVarExp
#   compound_pathview = rescale_to_min1_max1(compound_pathview) # rescale to [-1,1]
#   names(compound_pathview) = result %>% select(KEGG) %>% pull
# 
#   pathview(gene.data=functional_pathview_data, cpd.data=compound_pathview, pathway.id=pathwayKO, species="ko", out.suffix=filename, kegg.dir=path, kegg.native=T, low=list(gene="red",cpd="red"), mid=list(gene="gray",cpd="gray"), high=list(gene="green",cpd="green"))
# }
```